### ISSUE TITLE
Asset Library Tracking

### ISSUE THREAD

**Issue by ashygee** [primer/presentations#1]
### Objective

Provide a running log of all of the illustrations, icons, and other assets for presentational work. All of the assets will be stored in Figma unless otherwise stated.

### Asset
- [x] [Octicons](https://www.figma.com/file/FP7lqd1V00LUaT5zvdklkkZr/Octicons)
- [x] [GH Marketing Icons](https://www.figma.com/file/mI7o0RNCbWFhckw2svxKsm/GitHub-Icons?node-id=0%3A1)
- [ ] ~[Site Illustrations (People)](https://www.figma.com/file/S3SsQV8iZbUU1w89hC7Ph8nV/Site-Illustrations-People)~ no longer in use
- [ ] Site Illustrations (Mona outline)

### Formats
- [x] Keynote
- [x] PowerPoint
- [x] Google Slides
- [ ] mdx-deck
- [ ] deckset

**Comment by ashygee** [comment]
Adding Octicons to the list as well as file formats

**Comment by yaili** [comment]
@ashygee I see we now have Figma as a format too. Can this issue be closed for now?

**Comment by ashygee** [comment]
Yeah I'll go ahead and close it
