### ISSUE TITLE
Presentation outreach

### ISSUE THREAD

**Issue by ashygee** [primer/presentations#12]
With the first iteration of the presentation system finished and tested, the next step is to share the deck. This issue is to track the next steps for adoption of the presentation deck.

### Next Steps
- [x] Write docs
- [x] Create versioning system and version current deck
- [x] Create team post
- [x] Create new site with blueprints (optional?]

**Comment by ashygee** [comment]
Team post up: https://team.githubapp.com/posts/32291
